apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: LoadBalancer
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 80         # External port
      targetPort: 3000 # Container port

